### PR TITLE
Fix building on Cygwin

### PR DESCRIPTION
**Pull request by facboy**
`lua-aho-corasick` also requires fixes at https://github.com/facboy/lua-aho-corasick

### CODE REVIEW

**Comment by vcunat** [comment]
Would it suffice to replace those `link_with: libkres_lib` by `link_with: kresd`?

Otherwise if someone builds with static libkres (`--default-library=static`) the overall size gets noticeably up (roughly by a megabyte on x86_64-linux).

Those modules will never be used in other way than getting loaded by kresd, so symbols from it and from libkresd will always be available.  I assume that you're running into some strictness here.

**Comment by vcunat** [comment]
Thanks.  I did some minor modifications of this PR, included lua-aho-corasick, ran our usual Linux + macOS CIs and opened as https://gitlab.nic.cz/knot/knot-resolver/-/merge_requests/1384

I think it shouldn't make any difference for MSYS2/Cygwin but I haven't tested that.  I don't expect we'll officially support these (soon).  Still, I see no hurry to merge so it would be nice if you sometime confirm that it still works for you.

**Comment by facboy** [comment]
thanks, i will check it out.  i have an update on `lmdb`, i can post on the original issue (https://gitlab.nic.cz/knot/knot-resolver/-/issues/781#note_272351)

**Comment by facboy** [comment]
This was merged upstream in https://gitlab.nic.cz/knot/knot-resolver/-/merge_requests/1384.

**Pull request closed without merging**
