### PR TITLE
Create build.rst

### PR DESCRIPTION
**Pull request by unicycle2**
Info about installing on FreeBSD (the port will soon be 1.3.0 also).

### CODE REVIEW

**Comment by vcunat** [comment]
@unicycle2: is there a canonical URL to the FreeBSD port for knot-resolver?

**Comment by vcunat** [comment]
Hmm, this one, I guess :-) https://www.freshports.org/dns/knot-resolver/

**Comment by unicycle2** [comment]
Yes, but that's a previous version. I'm trying to upgrade it, but this was needed (plus it's depending on the knot2 port - which on i386 has atomic issues)

**Comment by vcunat** [comment]
Yes, I meant putting that link into the readme, as it seems "stable on updates".  BTW, knot-resolver should work OK even with older knot2 &ndash; I see 2.4.3 in there, that's not old at all.

**Comment by unicycle2** [comment]
True, but the knot2 port currently fails to install on i386. I'm (again) trying to fix it for the 2.5.1 release, and am convinced it's possible, but didn't found the correct solution - yet.

I still would like to try to have some way to have the knot2 port only install libknot when it is installed as dependency of knot-resolver.

Work in progress / but anything else than i386 works fine.

This request an be closed (?).

**Pull request closed without merging**
